version: "3"
services:
  react-app:
    image:  josip/todo-app
    stdin_open: true
    ports:
      - "5000:5000"
  api-server:
    image: josip/todo-api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.23-xenial
    ports:
      - "27017:27017"



